export const TRAINING_PHRASES = Object.freeze([
  "Hola, soy Xerach, te ayudo a diseñar la arquitectura de tu aplicación a medida.",
  "La clave está en escalar sin deuda técnica ni costes cloud desorbitados.",
  "Implementamos Next.js con NestJS y PostgreSQL para máxima robustez.",
  "¿Cuántos usuarios concurrentes gestiona tu plataforma actualmente?",
  "Transformamos procesos caóticos de Excel en sistemas automatizados.",
  "El roadmap incluye discovery técnico, MVP y hardening progresivo.",
  "Optimizamos la base de datos con réplicas de lectura y caché en Redis.",
  "Buenos días, revisemos juntos el flujo de remisiones veterinarias.",
  "Nuestro enfoque es pragmático: sin humo, sin vendor lock-in, código tuyo.",
  "La observabilidad con OpenTelemetry nos permite detectar cuellos de botella.",
  "Trescientos usuarios diarios generan aproximadamente mil transacciones críticas.",
  "¿Qué herramientas utilizas hoy? CRM, Holded, Google Calendar, WordPress.",
  "Automatizar la facturación reduce un treinta por ciento los errores humanos.",
  "Diseñamos APIs tipadas con tRPC, seguras y ultra rápidas en el edge.",
  "La experiencia de usuario es tan importante como la arquitectura limpia.",
  "En casos de picos de tráfico, utilizamos colas con BullMQ para no perder datos.",
  "Hola, soy tu gemelo digital, tu experto tecnológico siempre disponible.",
  "Evaluamos costes ocultos y proponemos ahorros inmediatos en AWS y Vercel.",
  "Una aplicación bien hecha factura mientras duermes, sin intervención manual.",
  "¿Cuál sería el indicador de éxito en seis meses? Menos no-shows, más ingresos.",
  "El programa de remisiones necesita trazabilidad, notificaciones y panel veterinario.",
  "Pronuncia con claridad: arquitectura, microservicios, escalabilidad, PostgreSQL.",
]);
